FROM node:16.19.0-alpine
WORKDIR /opt/myapp
RUN apk add build-base=0.5-r3 && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm ci
COPY . .
# your package.json should have a corresponding server script you could alternately use an entrypoint
CMD ["npm", "run", "server"]